  Future<void> _processAndUploadResults(String videoPath, GameModel game, String matchId, String screenshotPath) async {
    try {
      final match = await _matchRepository.listenToMatch(matchId).first;
      if (match == null) {
        throw Exception('Match not found');
      }

      final ocrText = await _performOcr(screenshotPath, game.ocrEngine);
      if (ocrText == null || ocrText.isEmpty) {
        await _flagForManualReview(match, 'OCR failed to extract text.', videoPath: videoPath, thumbnailPath: screenshotPath);
        return;
      }

      final parser = ScoreParserFactory.getParser(game);
      final parsedResult = parser.parse(ocrText);

      // Determine winner
      String? winnerId;
      if (parsedResult.player1Score != null && parsedResult.player2Score != null) {
        if (parsedResult.player1Score! > parsedResult.player2Score!) {
          winnerId = match.creatorId;
        } else if (parsedResult.player2Score! > parsedResult.player1Score!) {
          winnerId = match.opponentId;
        }
      }

      final gameResult = GameResultModel(
        id: '', // Will be generated by Firestore
        matchId: matchId,
        player1Id: match.creatorId,
        player2Id: match.opponentId,
        player1Score: parsedResult.player1Score,
        player2Score: parsedResult.player2Score,
        winnerId: winnerId,
        createdAt: DateTime.now(),
      );

      await _uploadResult(gameResult, videoPath, screenshotPath);
    } catch (e) {
      // Since we don't have the match object here, we can't flag for manual review in the same way.
      // For now, we will log the error. A more robust solution would be to pass the match object to this method.
      // TODO: Log error
    }
  }

  Future<void> _uploadResult(GameResultModel result, String videoPath, String thumbnailPath) async {
    final storageRef = FirebaseStorage.instance.ref();
    final videoFile = File(videoPath);
    final thumbnailFile = File(thumbnailPath);

    final videoUploadTask = storageRef.child('match_recordings/${result.matchId}.mp4').putFile(videoFile);
    final thumbnailUploadTask = storageRef.child('match_thumbnails/${result.matchId}.png').putFile(thumbnailFile);

    await Future.wait([videoUploadTask, thumbnailUploadTask]);

    await _gameResultRepository.createGameResult(result);

    AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: 2,
        channelKey: 'basic_channel',
        title: 'Match Finished 🎯',
        body: 'Results captured — tap to review on VerzusXYZ',
        payload: {'matchId': result.matchId},
      ),
    );
  }

  Future<void> _flagForManualReview(MatchModel match, String reason, {String? videoPath, String? thumbnailPath}) async {
    String? videoUrl;
    String? thumbnailUrl;

    if (videoPath != null) {
      final storageRef = FirebaseStorage.instance.ref();
      final videoFile = File(videoPath);
      final videoUploadTask = await storageRef.child('match_recordings/${match.id}.mp4').putFile(videoFile);
      videoUrl = await videoUploadTask.ref.getDownloadURL();
    }

    if (thumbnailPath != null) {
      final storageRef = FirebaseStorage.instance.ref();
      final thumbnailFile = File(thumbnailPath);
      final thumbnailUploadTask = await storageRef.child('match_thumbnails/${match.id}.png').putFile(thumbnailFile);
      thumbnailUrl = await thumbnailUploadTask.ref.getDownloadURL();
    }

    // We are not creating a game result here, but we could create a "disputed" or "review" document in a separate collection.
    // For now, we will just log the error.
    // TODO: Implement a proper manual review system.
  }
