// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxy6N71f-X7H6_IK9dGFumXqGtd1nMnic',
    appId: '1:132416276840:web:03970598c8d6fead872edd',
    messagingSenderId: '132416276840',
    projectId: 'verzusxyz',
    authDomain: 'verzusxyz.firebaseapp.com',
    databaseURL: 'https://verzusxyz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verzusxyz.firebasestorage.app',
    measurementId: 'G-R3LFHVFQJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuSpo-25xm3o4yWUhWOh8bqLNkUnRq3lk',
    appId: '1:132416276840:android:5c8b48170f5d2d65872edd',
    messagingSenderId: '132416276840',
    projectId: 'verzusxyz',
    databaseURL: 'https://verzusxyz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verzusxyz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaQ98B4L4FVB_h_zgR7615vHnzOzCsrU4',
    appId: '1:132416276840:ios:6380a0815a895adf872edd',
    messagingSenderId: '132416276840',
    projectId: 'verzusxyz',
    databaseURL: 'https://verzusxyz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verzusxyz.firebasestorage.app',
    iosBundleId: 'aa.verzus.xyz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaQ98B4L4FVB_h_zgR7615vHnzOzCsrU4',
    appId: '1:132416276840:ios:6380a0815a895adf872edd',
    messagingSenderId: '132416276840',
    projectId: 'verzusxyz',
    databaseURL: 'https://verzusxyz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verzusxyz.firebasestorage.app',
    iosBundleId: 'aa.verzus.xyz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxy6N71f-X7H6_IK9dGFumXqGtd1nMnic',
    appId: '1:132416276840:web:33456f127fd64b65872edd',
    messagingSenderId: '132416276840',
    projectId: 'verzusxyz',
    authDomain: 'verzusxyz.firebaseapp.com',
    databaseURL: 'https://verzusxyz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verzusxyz.firebasestorage.app',
    measurementId: 'G-DPCFS4V2J2',
  );

}