// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKo-pZ6vrbQdlxflt2T3VamNks9JSQu9s',
    appId: '1:5225172458:web:cc6b6e1172a01bce0fb693',
    messagingSenderId: '5225172458',
    projectId: 'ic1dwe87k4yifqbtntk1cb4e2559gx',
    authDomain: 'ic1dwe87k4yifqbtntk1cb4e2559gx.firebaseapp.com',
    storageBucket: 'ic1dwe87k4yifqbtntk1cb4e2559gx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8h_6hMe8FlzUP1DzKYflgh0huO7tzf1A',
    appId: '1:5225172458:android:37266a1b24a134a20fb693',
    messagingSenderId: '5225172458',
    projectId: 'ic1dwe87k4yifqbtntk1cb4e2559gx',
    storageBucket: 'ic1dwe87k4yifqbtntk1cb4e2559gx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORi_XlwHPdgM1uGhs3h9qk9rooshhtr4',
    appId: '1:5225172458:ios:f7df1cef288d70d70fb693',
    messagingSenderId: '5225172458',
    projectId: 'ic1dwe87k4yifqbtntk1cb4e2559gx',
    storageBucket: 'ic1dwe87k4yifqbtntk1cb4e2559gx.firebasestorage.app',
    iosBundleId: 'aa.verzus.xyz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORi_XlwHPdgM1uGhs3h9qk9rooshhtr4',
    appId: '1:5225172458:ios:f7df1cef288d70d70fb693',
    messagingSenderId: '5225172458',
    projectId: 'ic1dwe87k4yifqbtntk1cb4e2559gx',
    storageBucket: 'ic1dwe87k4yifqbtntk1cb4e2559gx.firebasestorage.app',
    iosBundleId: 'aa.verzus.xyz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKo-pZ6vrbQdlxflt2T3VamNks9JSQu9s',
    appId: '1:5225172458:web:28a6412ed1f448a50fb693',
    messagingSenderId: '5225172458',
    projectId: 'ic1dwe87k4yifqbtntk1cb4e2559gx',
    authDomain: 'ic1dwe87k4yifqbtntk1cb4e2559gx.firebaseapp.com',
    storageBucket: 'ic1dwe87k4yifqbtntk1cb4e2559gx.firebasestorage.app',
  );

}